# profile관리
spring:
  profiles:
    default: test
#    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: info
    com.sh: debug

  # 공통 jpa 설정
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none

  # NCP 클라우드 설정
cloud:
  aws:
    credentials:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}
    region:
      static: kr-standard
    stack:
      auto: false
    endpoint: https://kr.object.ncloudstorage.com

application:
  bucket:
    name: pettopia-bucket
  #  user-id: ssgback3-3
file:
  upload-dir: /path/to/upload/directory
